name: boss_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  intl: ^0.19.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  firebase_analytics: ^11.3.6
  fluttertoast: ^8.2.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_functions: ^5.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^1.1.0
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/boss_white.png"

flutter:
  uses-material-design: true
  assets:
   - assets/logo/boss_white.png
   - assets/logo/boss_colored.png
   - assets/images/people_office.jpeg
   - assets/images/money.jpg
   - assets/images/shake-hands.jpg
   



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
