
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
              'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCVfD85C6YIieS8K9OLvVBX93XdHxrMPWg',
      authDomain: 'boss-app-59402.firebaseapp.com',
      projectId: 'boss-app-59402',
      storageBucket: 'boss-app-59402.firebasestorage.app',
      messagingSenderId: '770542447983',
      appId: '1:770542447983:web:990735be40a12fd9b50c9a',
      measurementId: 'G-HEC7YD8H8W'
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCsjJZhOa27ZU--JdphvM6Hl-_vt0Y8UbA',
      appId: '1:770542447983:android:ea12b2386df548d0b50c9a',
      messagingSenderId: '770542447983',
      projectId: 'boss-app-59402',
      storageBucket: 'boss-app-59402.firebasestorage.app'
  );
}
